
[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

#decorations = "Buttonless"

#opacity = 0.7
#blur = true

option_as_alt = "Both"

[font]
normal.family = "CaskaydiaMono Nerd Font"
size = 16
[font.offset]
x = 0
y = 1

[general]
import = ["~/.config/alacritty/tokyo-night.toml"]
